<?php

return [
  // osteria
  // romana
  [ "user_id" => "1",
    "name" => "spaghetti alla carbonara",
    "ingredients" => 
        "uova,
        guanciale,
        pepe",
    
    "description" => "La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso.",
    "price" => "7.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "amatriciana",
    "ingredients" => 
        "guanciale,
        pecorino,
        pepe"
    ,
    "description" => "L'amatriciana (matriciana in romanesco) è un condimento per la pasta tipico della tradizione gastronomica di Amatrice",
    "price" => "6.45",
    "cover" => "",
    "visible" => true,
  ],
  // milanese
  [ "user_id" => "2",
    "name" => "cotoletta alla milanese",
    "ingredients" => 
        "costoletta di vitello,
        uova,
        pepe
        farina"
    ,
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "risotto alla milanese",
    "ingredients" => 
        "riso,
        zafferano"
    ,
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "8.45",
    "cover" => "",
    "visible" => true,
  ],
  // bolognes
  [ "user_id" => "3",
    "name" => "Tortellini in brodo",
    "ingredients" => 
        "tortellini,
        brodo di manzo"
    ,
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Lasagna",
    "ingredients" => 
        "sfoglia,
        besciamella,
        ragù"
    ,
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "",
    "visible" => true,
  ],
  //napoletana
  [ "user_id" => "4",
    "name" => "pasta e patate",
    "ingredients" => 
        "patate,
        carote,
        pepe,
        olio"
    ,
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Cuoppo di mare",
    "ingredients" => 
        "calamari,
        gamberi,
        triglia,
        semola,
        olio"
    ,
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "",
    "visible" => true,
  ],
  // barese
  [ "user_id" => "5",
    "name" => "Orecchiette con le cime rape",
    "ingredients" => 
        "cime di rapa,
        aglio,
        acciughe,
        olio"
    ,
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Tiella",
    "ingredients" => 
        "pepe,
        polpo,
        pomodori,
        olio,
        patate,
        riso,
        cozze"
    ,
    "description" => "La tiella alla barese di patate, riso e cozze è una pietanza tipica della cucina barese",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  // BAR
  [ "user_id" => "6",
  "name" => "cornetto",
  "ingredients" => 
      "acqua,
      farina,
      zucchero,
      lievito"
  ,
  "description" => "Cornetti Fragranti , anche da asporto",
  "price" => "6.30",
  "cover" => "",
  "visible" => true,
],
[ "user_id" => "6",
  "name" => "Shkaer",
  "ingredients" => 
      "latte,
       caffè,
      cioccolato" 
  ,
  "description" => "Latte caffe e cioccolato shakerati con tanto amore",
  "price" => "8.50",
  "cover" => "",
  "visible" => true,
],
[ "user_id" => "7",
"name" => "cornetto",
"ingredients" => 
"acqua,
farina,
zucchero,
lievito"
,
"description" => "Cornetti Fragranti , anche da asporto",
"price" => "6.30",
"cover" => "",
"visible" => true,
],

[ "user_id" => "7",
"name" => "Shkaer",
"ingredients" => 
"latte,
caffè,
cioccolato" 
,
"description" => "Latte caffe e cioccolato shakerati con tanto amore",
"price" => "8.50",
"cover" => "",
"visible" => true,
],

[ "user_id" => "8",
"name" => "cornetto",
"ingredients" => 
"acqua,
farina,
zucchero,
lievito"
,
"description" => "Cornetti Fragranti , anche da asporto",
"price" => "6.30",
"cover" => "",
"visible" => true,
],
[ "user_id" => "8",
"name" => "Shkaer",
"ingredients" => 
"latte,
caffè,
cioccolato"
,
"description" => "Latte caffe e cioccolato shakerati con tanto amore",
"price" => "8.50",
"cover" => "",
"visible" => true,
],
[ "user_id" => "9",
"name" => "cornetto",
"ingredients" => 
"acqua,
farina,
zucchero,
lievito"
,
"description" => "Cornetti Fragranti , anche da asporto",
"price" => "6.30",
"cover" => "",
"visible" => true,
],
[ "user_id" => "9",
"name" => "Shkaer",
"ingredients" => 
"latte,
caffè,
cioccolato"
,
"description" => "Latte caffe e cioccolato shakerati con tanto amore",
"price" => "8.50",
"cover" => "",
"visible" => true,
],
[ "user_id" => "10",
"name" => "cornetto",
"ingredients" => 
"acqua,
farina,
zucchero,
lievito"
,
"description" => "Cornetti Fragranti , anche da asporto",
"price" => "6.30",
"cover" => "",
"visible" => true,
],
[ "user_id" => "10",
"name" => "Shkaer",
"ingredients" => 
"latte,
caffè,
cioccolato"
,
"description" => "Latte caffe e cioccolato shakerati con tanto amore",
"price" => "8.50",
"cover" => "",
"visible" => true,
],
  // Burger King
  [ "user_id" => "11",
    "name" => "Cheeseburger",
    "ingredients" =>
        "panino,
        formaggio,
        hamburger,
        insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "11",
    "name" => "Whopper",
    "ingredients" =>
        "panino,
        sottilette,
        hamburger,
        bacon,
        pomodoro"
    ,
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "12",
    "name" => "Cheeseburger",
    "ingredients" =>
        "panino,
        formaggio,
        hamburger,
        insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "12",
    "name" => "Whopper",
    "ingredients" =>
        "panino,
        sottilette,
        hamburger,
        bacon,
        pomodoro"
    ,
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // McDonald
  [ "user_id" => "13",
    "name" => "Gran Crispy McBacon",
    "ingredients" => 
        "panino,
        hamburger,
        formaggio,
        salsa crispy,
        bacon"
    ,
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "13",
    "name" => "McChicken",
    "ingredients" => 
        "panino,
        petto di pollo,
        inslata,
        salsa mcChicken"
    ,
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "14",
    "name" => "Gran Crispy McBacon",
    "ingredients" => 
      "panino,
        hamburger,
        formaggio,
        salsa crispy,
        bacon"
    ,
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "14",
    "name" => "McChicken",
    "ingredients" => 
        "panino,
        petto di pollo,
        inslata,
        salsa mcChicken"
    ,
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  //fast food
  [ "user_id" => "15",
    "name" => "Crocchette di pollo",
    "ingredients" => 
        "
        petto di pollo,
        inslata,
        salsa mcChicken"
    ,
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "15",
    "name" => "Panzerotti",
    "ingredients" => 
        "pomodoro,
        mozzarella,
        pepe,
        olio"
    ,
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
],
[ "user_id" => "16",
  "name" => "Crocchette di pollo",
  "ingredients" =>
      "panino,
      petto di pollo,
      inslata,
      salsa mcChicken",
  "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
  "price" => "3.90",
  "cover" => "",
  "visible" => true,
],
[ "user_id" => "16",
  "name" => "Panzerotti",
  "ingredients" => 
      "pomodoro,
      mozzarella,
      pepe,
      olio",
  "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
  "price" => "3.40",
  "cover" => "",
  "visible" => true,
],
[ "user_id" => "17",
"name" => "Crocchette di pollo",
"ingredients" => 
    "panino,
    petto di pollo,
    inslata,
    salsa mcChicken",
"description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
"price" => "3.90",
"cover" => "",
"visible" => true,
],
[ "user_id" => "17",
"name" => "Panzerotti",
"ingredients" => 
    "pomodoro,
    mozzarella,
    pepe,
    olio",
"description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
"price" => "3.40",
"cover" => "",
"visible" => true,
],
[ "user_id" => "18",
"name" => "Crocchette di pollo",
"ingredients" =>
    "panino,
    petto di pollo,
    insalata,
    salsa mcChicken",
"description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
"price" => "3.90",
"cover" => "",
"visible" => true,
],
[ "user_id" => "18",
"name" => "Panzerotti",
"ingredients" =>
    "pomodoro,
    mozzarella,
    pepe,
    olio",
"description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
"price" => "3.40",
"cover" => "",
"visible" => true,
],
[ "user_id" => "19",
"name" => "Crocchette di pollo",
"ingredients" => 
    "panino,
    petto di pollo,
    inslata,
    salsa mcChicken",
"description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
"price" => "3.90",
"cover" => "",
"visible" => true,
],
[ "user_id" => "19",
"name" => "Panzerotti",
"ingredients" => 
    "pomodoro,
    mozzarella,
    pepe,
    olio",
"description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
"price" => "3.40",
"cover" => "",
"visible" => true,
],
  //pizza
  [ "user_id" => "20",
    "name" => "Margherita",
    "ingredients" => 
        "pomodoro,
        mozzarella,
        olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "20",
    "name" => "Quattro stagioni",
    "ingredients" => 
        "carciofi,
        mozzarella,
        olio,
        funghi,
        Prosciutto cotto,
        olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "21",
    "name" => "Margherita",
    "ingredients" =>
        "pomodoro,
        mozzarella,
        olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "21",
    "name" => "Quattro stagioni",
    "ingredients" => 
        "carciofi,
        mozzarella,
        olio,
        funghi,
        Prosciutto cotto,
        olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "22",
    "name" => "Margherita",
    "ingredients" => 
        "pomodoro,
        mozzarella,
        olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "22",
    "name" => "Quattro stagioni",
    "ingredients" =>
        "carciofi,
        mozzarella,
        olio,
        funghi,
        Prosciutto cotto,
        olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "23",
    "name" => "Margherita",
    "ingredients" =>
        "pomodoro,
        mozzarella,
        olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "23",
    "name" => "Quattro stagioni",
    "ingredients" => 
        "carciofi,
        mozzarella,
        olio,
        funghi,
        Prosciutto cotto,
        olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "24",
    "name" => "Margherita",
    "ingredients" => 
        "pomodoro,
        mozzarella,
        olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "24",
    "name" => "Quattro stagioni",
    "ingredients" => 
        "carciofi,
        mozzarella,
        olio,
        funghi,
        Prosciutto cotto,
        olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // cinese
  [ "user_id" => "25",
    "name" => "Uramaki",
    "ingredients" => 
        "riso,
        alga,
        avocado,
        polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "25",
    "name" => "Nigiri",
    "ingredients" => 
        "riso,
        filetto di salmone,
        branzino,
        filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "26",
  "name" => "Uramaki",
  "ingredients" => 
      "riso,
      alga,
      avocado,
      polpa di granchio",
  "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
  "price" => "8.50",
  "cover" => "",
  "visible" => true,
],
[ "user_id" => "26",
  "name" => "Nigiri",
  "ingredients" => 
      "riso,
      filetto di salmone,
      branzino,
      filetto di tonno",
  "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
  "price" => "8.00",
  "cover" => "",
  "visible" => true,
],
[ "user_id" => "27",
"name" => "Uramaki",
"ingredients" => 
    "riso,
    alga,
    avocado,
    polpa di granchio",
"description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
"price" => "8.50",
"cover" => "",
"visible" => true,
],
[ "user_id" => "27",
"name" => "Nigiri",
"ingredients" =>
    "riso,
    filetto di salmone,
    branzino,
    filetto di tonno",
"description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
"price" => "8.00",
"cover" => "",
"visible" => true,
],
[ "user_id" => "28",
"name" => "Uramaki",
"ingredients" => 
    "riso,
    alga,
    avocado,
    polpa di granchio",
"description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
"price" => "8.50",
"cover" => "",
"visible" => true,
],
[ "user_id" => "28",
"name" => "Nigiri",
"ingredients" =>
    "riso,
    filetto di salmone,
    branzino,
    filetto di tonno",
"description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
"price" => "8.00",
"cover" => "",
"visible" => true,
],
[ "user_id" => "29",
"name" => "Uramaki",
"ingredients" =>
    "riso,
    alga,
    avocado,
    polpa di granchio",
"description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
"price" => "8.50",
"cover" => "",
"visible" => true,
],
[ "user_id" => "29",
"name" => "Nigiri",
"ingredients" => 
    "riso,
    filetto di salmone,
    branzino,
    filetto di tonno",
"description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
"price" => "8.00",
"cover" => "",
"visible" => true,
],
  
];
