<?php

use Illuminate\Support\Facades\Config;

return [
  // 1
  [ "user_id" => "1",
    "name" => "spaghetti alla carbonara",
    "ingredients" => "uova, guanciale, pepe",
    "description" => "La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso.",
    "price" => "7.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "amatriciana",
    "ingredients" => "guanciale, pecorino, pepe",
    "description" => "L'amatriciana (matriciana in romanesco) è un condimento per la pasta tipico della tradizione gastronomica di Amatrice",
    "price" => "6.45",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "spaghetti alla gricia",
    "ingredients" => "uova, guanciale, pepe",
    "description" => "La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso.",
    "price" => "7.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "amatriciana gourmet",
    "ingredients" => "guanciale, pecorino, pepe",
    "description" => "L'amatriciana (matriciana in romanesco) è un condimento per la pasta tipico della tradizione gastronomica di Amatrice",
    "price" => "6.45",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "spaghetti alla carbonara maxi",
    "ingredients" => "uova, guanciale, pepe",
    "description" => "La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso.",
    "price" => "7.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "amatriciana light",
    "ingredients" => "guanciale, pecorino, pepe",
    "description" => "L'amatriciana (matriciana in romanesco) è un condimento per la pasta tipico della tradizione gastronomica di Amatrice",
    "price" => "6.45",
    "cover" => "",
    "visible" => true,
  ],
  // 2
  [ "user_id" => "2",
    "name" => "cotoletta alla milanese",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "risotto alla milanese",
    "ingredients" => "riso, zafferano",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "8.45",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "cotoletta semplice",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "risotto allo zafferano",
    "ingredients" => "riso, zafferano",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "8.45",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "carne in pastella",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "risotto con funghi",
    "ingredients" => "riso, zafferano",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "8.45",
    "cover" => "",
    "visible" => true,
  ],
  // 3
  [ "user_id" => "3",
    "name" => "Tortellini in brodo",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Lasagna",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Tortellini in ragù",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Lasagna bianca",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Tortellini in brodo vegetale",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Lasagna Quattro Stagioni",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "",
    "visible" => true,
  ],
  // 4
  [ "user_id" => "4",
    "name" => "pasta e patate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Cuoppo di mare",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "pasta, polipo epatate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Cuoppo di mare maxi",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "pasta speck e patate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Cuoppo di mare dolce",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "",
    "visible" => true,
  ],
  // 5
  [ "user_id" => "5",
    "name" => "Orecchiette con le cime rape",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Tiella",
    "ingredients" => "pepe, polpo, pomodori, olio, patate, riso, cozze",
    "description" => "La tiella alla barese di patate, riso e cozze è una pietanza tipica della cucina barese",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Orecchiette con sugo",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Tiella maxi",
    "ingredients" => "pepe, polpo, pomodori, olio, patate, riso, cozze",
    "description" => "La tiella alla barese di patate, riso e cozze è una pietanza tipica della cucina barese",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Orecchiette alle zucchine",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Tiella Reale",
    "ingredients" => "pepe, polpo, pomodori, olio, patate, riso, cozze",
    "description" => "La tiella alla barese di patate, riso e cozze è una pietanza tipica della cucina barese",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  // 6
  [ 
    "user_id" => "6",
    "name" => "cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Shakaer",
    "ingredients" => 
      "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "6",
    "name" => "brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Milkshake",
    "ingredients" => 
      "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "6",
    "name" => "Bomba alla crema",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Caffè Americano",
    "ingredients" => 
      "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  // 7
  [ 
    "user_id" => "7",
    "name" => "cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "7",
    "name" => "Shakaer",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "7",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "7",
    "name" => "Bomba alla crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "7",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "7",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
 // 8
  [ 
    "user_id" => "8",
    "name" => "cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "8",
    "name" => "Shkaer",
    "ingredients" => "latte, caffè, cioccolato",
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "8",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "8",
    "name" => "Bomba alla crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "8",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "8",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  // 9
  [ 
    "user_id" => "9",
    "name" => "cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "9",
    "name" => "Shkaer",
    "ingredients" => "latte, caffè, cioccolato",
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "9",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "9",
    "name" => "Bomba alla crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "9",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "9",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  // 10
  [ 
    "user_id" => "10",
    "name" => "cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "10",
    "name" => "Shkaer",
    "ingredients" => "latte, caffè, cioccolato",
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "10",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "10",
    "name" => "Bomba alla crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "10",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "10",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  // 11
  [ 
    "user_id" => "11",
    "name" => "Cheeseburger",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "11",
    "name" => "Whopper",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "11",
    "name" => "Double Cheeseburger",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "11",
    "name" => "Whopper Maxi",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // 12
  [ 
    "user_id" => "12",
    "name" => "Cheeseburger",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "12",
    "name" => "Whopper",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "12",
    "name" => "Cheeseburger Maxi",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "12",
    "name" => "Whopper Double",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "12",
    "name" => "Cheeseburger con bacon",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "12",
    "name" => "Big Mac",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // 13
  [ 
    "user_id" => "13",
    "name" => "Gran Crispy McBacon",
    "ingredients" =>  "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "13",
    "name" => "McChicken",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "13",
    "name" => "Big Mac",
    "ingredients" =>  "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "13",
    "name" => "MySelection Chicken",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "13",
    "name" => "Gran Crispy McBacon doppio",
    "ingredients" =>  "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "13",
    "name" => "McChicken Pepper",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  // 14
  [ 
    "user_id" => "14",
    "name" => "Gran Crispy McBacon",
    "ingredients" => "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "14",
    "name" => "McChicken",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "14",
    "name" => "Gran Big Mac",
    "ingredients" => "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "14",
    "name" => "Double McChicken",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "14",
    "name" => "Gran Whopper",
    "ingredients" => "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "14",
    "name" => "McChicken Pepper",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  // 15
  [ 
    "user_id" => "15",
    "name" => "Crocchette di pollo",
    "ingredients" => "petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "15",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "15",
    "name" => "Nuggets",
    "ingredients" => "petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "15",
    "name" => "Pizzetta",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "15",
    "name" => "Crocchette di pollo light",
    "ingredients" => "petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "15",
    "name" => "Panzerotti piccanti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // 16
  [ 
    "user_id" => "16",
    "name" => "Crocchette di pollo",
    "ingredients" =>"panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "16",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "16",
    "name" => "Crocchette di pollo piccanti",
    "ingredients" =>"panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "16",
    "name" => "Panzerotti integrali",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "16",
    "name" => "Crocchette di mozzarella",
    "ingredients" =>"panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "16",
    "name" => "Panzerotti alle patate",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // 17
  [ "user_id" => "17",
    "name" => "Crocchette di pollo",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Crocchette di pollo light",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Panzerotti alle patate",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Pepite di speck",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Panzerotti Maxi",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // 18
  [ "user_id" => "18",
    "name" => "Crocchette di pollo",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "18",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "18",
    "name" => "Crocchette di pollo Maxi",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "18",
    "name" => "Panzerotti dolci",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "18",
    "name" => "Chicken Wings",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "18",
    "name" => "Panzerotti al pomodoro",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // 19
  [ 
    "user_id" => "19",
    "name" => "Crocchette di pollo",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "19",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "19",
    "name" => "Crocchette di pollo doppie",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "19",
    "name" => "Panzerotti fritti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "19",
    "name" => "nuggets Americani",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "19",
    "name" => "Panzerotti fritti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  // 20
  [ 
    "user_id" => "20",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "20",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "20",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "20",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "20",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "20",
    "name" => "Funghi e cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 21
  [ 
    "user_id" => "21",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "21",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "21",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "21",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "21",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "21",
    "name" => "Funghi e cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 22
  [ 
    "user_id" => "22",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "22",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "22",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "22",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "22",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "22",
    "name" => "Funghi e cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 23
  [ 
    "user_id" => "23",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "23",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "23",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "23",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "23",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "23",
    "name" => "Funghi e cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 24
  [ 
    "user_id" => "24",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "24",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "24",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "24",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "24",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "24",
    "name" => "Funghi e cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 25
  [ 
    "user_id" => "25",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "25",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "25",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "25",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "25",
    "name" => "Uramaki di pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "25",
    "name" => "Barca di sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "",
    "visible" => true,
  ],
  // 26
  [ 
    "user_id" => "26",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "26",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "26",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "26",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "26",
    "name" => "Uramaki di pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "26",
    "name" => "Barca di sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "",
    "visible" => true,
  ],
  // 27
  [ 
    "user_id" => "27",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "27",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "27",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "27",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "27",
    "name" => "Uramaki di pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "27",
    "name" => "Barca di sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "",
    "visible" => true,
  ],
  // 28
  [ 
    "user_id" => "28",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "28",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "28",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "28",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "28",
    "name" => "Uramaki di pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "28",
    "name" => "Barca di sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "",
    "visible" => true,
  ],
  // 29
  [ 
    "user_id" => "29",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "29",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "29",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "29",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "29",
    "name" => "Uramaki di pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "29",
    "name" => "Barca di sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "",
    "visible" => true,
  ],
  //30
  [ 
    "user_id" => "30",
    "name" => "Pizza fritta gourmet",
    "ingredients" => "pastella, olio, prosciutto crudo, pecorino",
    "description" => "Deliziose pizze fritte con selezione di salumi e formaggi",
    "price" => "9.80",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "30",
    "name" => "Trippa di maiale",
    "ingredients" => "Budella di maiale, passata di pomodoro, pepe",
    "description" => "Trippa al sugo buonissima",
    "price" => "5.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "30",
    "name" => "Crocchette di pollo",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "30",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "30",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "30",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 31
  [ 
    "user_id" => "31",
    "name" => "Pizza fritta gourmet",
    "ingredients" => "pastella, olio, gambero, pecorino",
    "description" => "Deliziose pizze fritte con selezione di pesce e formaggi",
    "price" => "9.80",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "31",
    "name" => "Trippa di branzino",
    "ingredients" => "Budella di branzino, passata di pomodoro, pepe",
    "description" => "Trippa al sugo buonissima",
    "price" => "5.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "31",
    "name" => "Crocchette di pesce",
    "ingredients" => "panino, pesce, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del pesce avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "31",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "31",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "31",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 32
  [ 
    "user_id" => "32",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "32",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "32",
    "name" => "Quattro stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "32",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "32",
    "name" => "Marinara",
    "ingredients" => "pomodoro, olio, aglio",
    "description" => "La pizza Marinara è la tipica pizza napoletana, condita con pomodoro e aglio",
    "price" => "5.80",
    "cover" => "",
    "visible" => true,
  ],
  [ 
    "user_id" => "32",
    "name" => "Pizza Patatine e Wurstel",
    "ingredients" => "patatine fritte, wurstel, pomodoro e mozzarella",
    "description" => "Classica pizza con base rossa e mozzarella, condita con patatine e wurstel",
    "price" => "5.70",
    "cover" => "",
    "visible" => true,
  ],
  // 33
  [ "user_id" => "33",
    "name" => "cotoletta alla milanese",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Tortellini in brodo",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Lasagna",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "",
    "visible" => true,
  ],

  [ "user_id" => "33",
    "name" => "pasta e patate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Cuoppo di mare",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Orecchiette con le cime rape",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "",
    "visible" => true,
  ],
];
