<?php

use Illuminate\Support\Facades\Config;

return [
  // 1
  [ "user_id" => "1",
    "name" => "Spaghetti Alla Carbonara",
    "ingredients" => "uova, guanciale, pepe",
    "description" => "La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso.",
    "price" => "7.00",
    "cover" => "https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2021/03/Carbonara-ricetta-5328.jpg",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "Amatriciana",
    "ingredients" => "guanciale, pecorino, pepe",
    "description" => "L'amatriciana (matriciana in romanesco) è un condimento per la pasta tipico della tradizione gastronomica di Amatrice",
    "price" => "6.45",
    "cover" => "https://www.conad.it/assets/images/ricette/dayone-ricette/s-d/s-d-bucatiniamatriciana.jpg",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "Spaghetti Alla Gricia",
    "ingredients" => "uova, guanciale, pepe",
    "description" => "La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso.",
    "price" => "7.00",
    "cover" => "https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2022/01/Pasta-alla-gricia-4870.jpg",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "Amatriciana Gourmet",
    "ingredients" => "guanciale, pecorino, pepe",
    "description" => "L'amatriciana (matriciana in romanesco) è un condimento per la pasta tipico della tradizione gastronomica di Amatrice",
    "price" => "6.45",
    "cover" => "https://www.academiabarilla.it/wp-content/uploads/2019/07/148.-Bucatini_Amatriciana_3.jpg",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "Spaghetti Alla Carbonara Maxi",
    "ingredients" => "uova, guanciale, pepe",
    "description" => "La pasta alla carbonara è un piatto caratteristico del Lazio, e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso.",
    "price" => "7.00",
    "cover" => "https://www.giallozafferano.it/images/150-15022/Carbonara-al-forno_780x520_wm.jpg",
    "visible" => true,
  ],
  [ "user_id" => "1",
    "name" => "Amatriciana Light",
    "ingredients" => "guanciale, pecorino, pepe",
    "description" => "L'amatriciana (matriciana in romanesco) è un condimento per la pasta tipico della tradizione gastronomica di Amatrice",
    "price" => "6.45",
    "cover" => "https://blog.giallozafferano.it/mortadifame/wp-content/uploads/2013/12/casarecce-amatriciana-evi.jpg",
    "visible" => true,
  ],
  // 2
  [ "user_id" => "2",
    "name" => "Cotoletta Alla Milanese",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "https://static.cookist.it/wp-content/uploads/sites/21/2018/11/cotoletta-alla-milanese.jpg",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "Risotto Alla Milanese",
    "ingredients" => "riso, zafferano",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "8.45",
    "cover" => "https://winedharma.com/wine-dharma/uploads/2020/10/Risotto-alla-milanese-ricetta-originale-con-zafferano-e-midollo-di-bue.jpg",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "Cotoletta Semplice",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "https://www.gustissimo.it/articoli/ricette/pollame/cotolette-di-pollo.jpg",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "Risotto Allo Zafferano",
    "ingredients" => "riso, zafferano",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "8.45",
    "cover" => "https://www.misya.info/wp-content/uploads/2016/01/Risotto-allo-zafferano.jpg",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "Carne In Pastella",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "https://www.iltarantino.it/wp-content/uploads/2020/03/pollo-in-pastella-ricetta.jpg",
    "visible" => true,
  ],
  [ "user_id" => "2",
    "name" => "Risotto Con Funghi",
    "ingredients" => "riso, zafferano",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "8.45",
    "cover" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2015/10/ricetta-risotto-funghi/_jcr_content/header-par/image-single.img.jpg/1443711515924.jpg",
    "visible" => true,
  ],
  // 3
  [ "user_id" => "3",
    "name" => "Tortellini In Brodo",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "https://www.brunobarbieri.blog/wp-content/uploads/2017/12/10112310/tortellini-in-brodo-blog.jpg",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Lasagna",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "https://www.ricettedellanonna.net/wp-content/uploads/2014/09/lasagne-al-ragu%CC%80.jpg",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Tortellini In Ragù",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "https://www.agrodolce.it/app/uploads/2013/11/ltort1.jpg",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Lasagna Bianca",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "https://www.piuricette.it/wp-content/uploads/2021/03/Schermata-2021-09-29-alle-19.31.28-770x500.png",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Tortellini In Brodo Vegetale",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "https://blog.giallozafferano.it/lamiacucinamoreefantasia/wp-content/uploads/2017/05/image-7.jpeg",
    "visible" => true,
  ],
  [ "user_id" => "3",
    "name" => "Lasagna Quattro Stagioni",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2020/02/4235_Lasagne.jpg?resize=895%2C616&ssl=1",
    "visible" => true,
  ],
  // 4
  [ "user_id" => "4",
    "name" => "Pasta E Patate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2016/01/Pasta-e-Patate-la-Ricetta-napoletana-Ricetta-Pasta-e-patate.jpg",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Cuoppo Di Mare",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/0e/ed/64/2a/cuoppo-di-mare-fried.jpg",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Pasta, Polipo Epatate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "https://www.lospicchiodaglio.it/img/ricette/pastapolpopatate.jpg",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Cuoppo Di Mare Maxi",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "https://www.dissapore.com/wp-content/uploads/2020/03/cuoppo-napoletano.jpg",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Pasta Speck E Patate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "https://www.fattoincasadabenedetta.it/wp-content/uploads/2020/02/pasta-con-crema-di-patate-e-speck.jpg",
    "visible" => true,
  ],
  [ "user_id" => "4",
    "name" => "Cuoppo Di Mare Dolce",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJKgEBBphP2ZXIXgaNlfCC9KsD4txGuX9fCA&usqp=CAU",
    "visible" => true,
  ],
  // 5
  [ "user_id" => "5",
    "name" => "Orecchiette Con Le Cime Rape",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "https://www.misya.info/wp-content/uploads/2011/11/orecchiette-alle-cime-di-rapa.jpg",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Tiella",
    "ingredients" => "pepe, polpo, pomodori, olio, patate, riso, cozze",
    "description" => "La tiella alla barese di patate, riso e cozze è una pietanza tipica della cucina barese",
    "price" => "8.50",
    "cover" => "https://www.melarossa.it/wp-content/uploads/2022/01/tiella-di-gaeta.jpg.webp?x97015",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Orecchiette Con Sugo",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "https://www.paneacquasale.it/wp-content/uploads/2018/09/orecchiette-con-polpettine-al-sugo-1.jpg",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Tiella Maxi",
    "ingredients" => "pepe, polpo, pomodori, olio, patate, riso, cozze",
    "description" => "La tiella alla barese di patate, riso e cozze è una pietanza tipica della cucina barese",
    "price" => "8.50",
    "cover" => "https://www.ditestaedigola.com/wp-content/uploads/2016/05/Tiellabanner.jpg",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Orecchiette Alle Zucchine",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "https://www.profumodibasilico.it/wp-content/uploads/2018/03/Orecchiette-al-pesto-di-zucchine_2000X1250-752x440.jpg",
    "visible" => true,
  ],
  [ "user_id" => "5",
    "name" => "Tiella Reale",
    "ingredients" => "pepe, polpo, pomodori, olio, patate, riso, cozze",
    "description" => "La tiella alla barese di patate, riso e cozze è una pietanza tipica della cucina barese",
    "price" => "8.50",
    "cover" => "https://thumbs.dreamstime.com/b/la-tiella-un-tipico-piatto-di-gaeta-%C3%A8-pronto-per-essere-mangiato-176265600.jpg",
    "visible" => true,
  ],
  // 6
  [
    "user_id" => "6",
    "name" => "Cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://wips.plug.it/cips/buonissimo.org/cms/2012/06/Cornetto.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Shakaer",
    "ingredients" =>
      "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2013/12/ricetta-caffe-shakerato-cioccolato-vaniglia/_jcr_content/header-par/image_single.img.jpg/1431097340144.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://www.fattoincasadabenedetta.it/wp-content/uploads/2020/05/brioche-col-tuppo.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Milkshake",
    "ingredients" =>
      "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://preppykitchen.com/wp-content/uploads/2021/04/Milkshake-Recipe-Card.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Bomba alla crema",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://blog.giallozafferano.it/allacciateilgrembiule/wp-content/uploads/2018/01/bomboloni-crema.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "6",
    "name" => "Caffè Americano",
    "ingredients" =>
      "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://primochef.it/wp-content/uploads/2021/03/SH_caffe_americano.jpg.webp",
    "visible" => true,
  ],
  // 7
  [
    "user_id" => "7",
    "name" => "Cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://wips.plug.it/cips/buonissimo.org/cms/2012/06/cornetto-alla-nutella.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "7",
    "name" => "Shakaer",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://www.runtastic.com/blog/wp-content/uploads/2018/07/coconut_coffee_smoothie_1200x800.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "7",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/2021-10/brioche%20col%20tuppo%20-%20Fine%20Dining%20Lovers.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "7",
    "name" => "Bomba Alla Crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://static.cookist.it/wp-content/uploads/sites/21/2019/07/bomboloni-alla-crema-1200x900.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "7",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://blog.giallozafferano.it/creandosiimpara/wp-content/uploads/2017/05/IMG_8202-720x494.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "7",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://hips.hearstapps.com/elleit.h-cdn.co/assets/17/35/1504004448-gettyimages-730190189.jpg",
    "visible" => true,
  ],
 // 8
  [
    "user_id" => "8",
    "name" => "Cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://www.caffecali.com/wp-content/uploads/2017/11/cornetto-colazione-caff%C3%A8-cal%C3%AC.jpg",
    "visible" => true,
  ],
  [ "user_id" => "8",
    "name" => "Shkaer",
    "ingredients" => "latte, caffè, cioccolato",
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://www.runtastic.com/blog/wp-content/uploads/2018/07/coconut_coffee_smoothie_1200x800.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "8",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2012/07/Brioche-siciliana-Brioche-col-tuppo-Ricetta-Brioche-siciliane.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "8",
    "name" => "Bomba Alla Crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://ricetta.it/Uploads/Imgs/bombe-fritte-ripiene-alla-crema-big.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "8",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://www.dolciprogetti.it/wp-content/uploads/2018/03/DSC_0278_010.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "8",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://www.royalcupcoffee.com/sites/default/files/images/blog_post/shutterstock_237082540.jpg",
    "visible" => true,
  ],
  // 9
  [
    "user_id" => "9",
    "name" => "Cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://a-modo-mio.at/wp-content/uploads/2021/08/7_cornetti16.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "9",
    "name" => "Shkaer",
    "ingredients" => "latte, caffè, cioccolato",
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://img.comeunochef.com/2021-07/caffe-con-cioccolato-peperoncino-e-vaniglia-1.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "9",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://biancolievito.it/wp-content/uploads/2016/05/shutterstock_1376663042.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "9",
    "name" => "Bomba Alla Crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://upload.wikimedia.org/wikipedia/commons/3/38/Bomboloni_con_marmellata.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "9",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://blog.giallozafferano.it/farinaezucchero/wp-content/uploads/2019/01/20190125_124209.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "9",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://media.soscuisine.com/images/recettes/large/3186.jpg",
    "visible" => true,
  ],
  // 10
  [
    "user_id" => "10",
    "name" => "Cornetto",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://www.giallozafferano.it/images/230-23060/Cornetti-con-lievito-madre_780x520_wm.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "10",
    "name" => "Shkaer",
    "ingredients" => "latte, caffè, cioccolato",
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://icetechice.com/blog/wp-content/uploads/2017/09/Caff%C3%A8-shakerato-destacada.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "10",
    "name" => "Brioche",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://www.lericette-bimby.it/wp-content/uploads/2022/03/BRIOCHE-CON-GOCCE-DI-CIOCCOLATO-BIMBY--1200x900.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "10",
    "name" => "Bomba alla crema",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/0a/eb/33/ca/bombe-alla-crema.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "10",
    "name" => "Pasta Danese",
    "ingredients" => "acqua, farina, zucchero, lievito",
    "description" => "Cornetti Fragranti , anche da asporto",
    "price" => "6.30",
    "cover" => "https://blog.giallozafferano.it/maniamore/wp-content/uploads/2020/06/DANESI-BRIOCHE-CREMA-E-UVETTA-5775-720x480.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "10",
    "name" => "Ice Coffee",
    "ingredients" => "latte, caffè, cioccolato" ,
    "description" => "Latte caffe e cioccolato shakerati con tanto amore",
    "price" => "8.50",
    "cover" => "https://www.tasteofhome.com/wp-content/uploads/2018/04/FT20_243550_F_0213_horiz.jpg",
    "visible" => true,
  ],
  // 11
  [
    "user_id" => "11",
    "name" => "Cheeseburger",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2016/10/1476372420_59c4aff95b38d46c4f202f6c0f9ef3bb3cfe0b3c-514487916.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "11",
    "name" => "Whopper",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "https://media-assets.wired.it/photos/615dabc704249cf3a9c84b94/master/pass/GettyImages-1160320532.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "11",
    "name" => "Double Cheeseburger",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "https://www.mcdonalds.it/sites/default/files/products/double-cheeseburger--isolated.png",
    "visible" => true,
  ],
  [
    "user_id" => "11",
    "name" => "Whopper Maxi",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "http://www.findtakeaways.co.za/images/Burger%20King%20Wednesday%20Whopper.PNG",
    "visible" => true,
  ],
  // 12
  [
    "user_id" => "12",
    "name" => "Cheeseburger",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "https://static9.depositphotos.com/1588534/1095/i/600/depositphotos_10957284-stock-photo-cheeseburger-and-french-fries.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "12",
    "name" => "Whopper",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "https://canadify.com/wp-content/uploads/2022/05/Burger-King-Canada-Offers-3-Whopper-Through-May-29-2022.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "12",
    "name" => "Cheeseburger Maxi",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "https://www.esselunga.it/cms/images/servizi/ricette-scontate/5%20hamburger/croccante-senape-miele.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "12",
    "name" => "Whopper Double",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "https://www.nicepng.com/png/detail/83-834338_burger-king-hungry-jacks-double-whopper.png",
    "visible" => true,
  ],
  [
    "user_id" => "12",
    "name" => "Cheeseburger Con Bacon",
    "ingredients" => "panino, formaggio, hamburger, insalata",
    "description" => "Quando si dice 'Cheeeeeese' sorridono tutti. Certo, perché a chi non verrebbe da pensare al nostro delizioso Cheeseburger: con delicato formaggio Cheddar fuso e carne di manzo cotta sulla fiamma viva. Allora, anche tu sorridi già?",
    "price" => "3.20",
    "cover" => "https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2016/10/1476377789_0b563e27ac4eef4682e3e059e115ad8d2bcc7474-299601403.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "12",
    "name" => "Big Mac",
    "ingredients" => "panino, sottilette, hamburger, bacon, pomodoro",
    "description" => "La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile.",
    "price" => "3.40",
    "cover" => "https://upload.wikimedia.org/wikipedia/commons/9/9a/Big_Mac_hamburger.jpg",
    "visible" => true,
  ],
  // 13
  [
    "user_id" => "13",
    "name" => "Gran Crispy McBacon",
    "ingredients" =>  "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/video/2021-12/gran-crispy-mcbacon_thumb.jpg.webp?itok=XUFHt6CA",
    "visible" => true,
  ],
  [
    "user_id" => "13",
    "name" => "McChicken",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxU2jAIxopH-97-x2JG5NKpKC_RiGVNAPdxbdvgGQzjWPYvJAAYWydx0HbadTOkHaZv1Y&usqp=CAU",
    "visible" => true,
  ],
  [
    "user_id" => "13",
    "name" => "Big Mac",
    "ingredients" =>  "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "https://www.junkfully.com/wp-content/uploads/2016/12/Big-Mac.png",
    "visible" => true,
  ],
  [
    "user_id" => "13",
    "name" => "MySelection Chicken",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://www.mcdonalds.it/sites/default/files/products/mys-chicken-asiago--hero-isolated.png",
    "visible" => true,
  ],
  [
    "user_id" => "13",
    "name" => "Gran Crispy McBacon doppio",
    "ingredients" =>  "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "https://www.scattidigusto.it/wp-content/uploads/2014/03/hamburger-Gran-Crispy-McBacon-1568x1045.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "13",
    "name" => "McChicken Pepper",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://fastfoodnutrition.org/item-photos/full/16171265423991.jpg",
    "visible" => true,
  ],
  // 14
  [
    "user_id" => "14",
    "name" => "Gran Crispy McBacon",
    "ingredients" => "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "https://www.scattidigusto.it/wp-content/uploads/2014/03/hamburger-Gran-Crispy-McBacon.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "14",
    "name" => "McChicken",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://www.giallozafferano.it/images/ricette/210/21061/foto_hd/hd780x520_wm.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "14",
    "name" => "Gran Big Mac",
    "ingredients" => "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpHou5-Ft2GT9SGOgvSPmv93i1dtNsYu_4Q&usqp=CAU",
    "visible" => true,
  ],
  [
    "user_id" => "14",
    "name" => "Double McChicken",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://www.mcdonalds.it/sites/default/files/products/double-chicken-bbq--hero-isolated.png",
    "visible" => true,
  ],
  [
    "user_id" => "14",
    "name" => "Gran Whopper",
    "ingredients" => "panino, hamburger, formaggio, salsa crispy, bacon",
    "description" => "Chi ama il Crispy McBacon® ne prenderebbe volentieri un altro e un altro e un altro e un altro ancora.",
    "price" => "4.10",
    "cover" => "https://static.gamberorosso.it/2021/05/king-rebel.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "14",
    "name" => "McChicken Pepper",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://assets3.thrillist.com/v1/image/2811552/1200x630/flatten;crop_down;webp=auto;jpeg_quality=70",
    "visible" => true,
  ],
  // 15
  [
    "user_id" => "15",
    "name" => "Crocchette Di Pollo",
    "ingredients" => "petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://static.cookist.it/wp-content/uploads/sites/21/2018/03/crocchette-di-pollo.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "15",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.fattoincasadabenedetta.it/wp-content/uploads/2020/04/PANZEROTTI-PUGLIESI-sito-stock.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "15",
    "name" => "Nuggets",
    "ingredients" => "petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://www.bofrost.ch/writable/products/images/10010.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "15",
    "name" => "Pizzetta",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.giallozafferano.it/images/221-22130/Pizzette-rosse_650x433_wm.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "15",
    "name" => "Crocchette Di Pollo Light",
    "ingredients" => "petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://blog.giallozafferano.it/laciambellasenzabuco/wp-content/uploads/2021/12/IMG_1258-960x640.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "15",
    "name" => "Panzerotti Piccanti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://blog.giallozafferano.it/piovonoricette/wp-content/uploads/2020/12/IMG_3337.jpg",
    "visible" => true,
  ],
  // 16
  [
    "user_id" => "16",
    "name" => "Crocchette Di Pollo",
    "ingredients" =>"panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://www.fattoincasadabenedetta.it/wp-content/uploads/2019/05/NuggetspolloYOUTUBE.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "16",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.giallozafferano.it/images/224-22433/Panzerotti-calzoni-fritti_650x433_wm.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "16",
    "name" => "Crocchette Di Pollo Piccanti",
    "ingredients" =>"panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://friggitriceadaria.online/wp-content/uploads/2017/11/ali-di-pollo-piccanti-870.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "16",
    "name" => "Panzerotti Integrali",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.cucina-naturale.it/wp-content/uploads/2017/02/20002Fpanzerottiripieniverza.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "16",
    "name" => "Crocchette Di Mozzarella",
    "ingredients" =>"panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://blog.giallozafferano.it/peperoncino88/wp-content/uploads/2017/02/DSC_0155.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "16",
    "name" => "Panzerotti Alle Patate",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://blog.giallozafferano.it/cucinafacileconelena/wp-content/uploads/2016/06/panzerotti-di-patate-fritti-1.jpg",
    "visible" => true,
  ],
  // 17
  [ "user_id" => "17",
    "name" => "Crocchette Di Pollo",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6NclD4y8Yb37VUozUhgblqI4lpSJZ7VspEQ&usqp=CAU",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://d2sj0xby2hzqoy.cloudfront.net/kenwood_italy/attachments/data/000/007/835/medium/panzerotti.jpg",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Crocchette Di Pollo Light",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://primochef.it/wp-content/uploads/2021/09/SH_nuggets_di_pollo.jpg.webpss",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Panzerotti Alle Patate",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.ferrariformaggi.it/crop.php?w=586&h=355&src=upload/panzerotti.jpg",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Pepite Di Speck",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://blog.giallozafferano.it/neltegamesulfuoco/wp-content/uploads/2020/04/pepiteasiagospeck.jpg",
    "visible" => true,
  ],
  [ "user_id" => "17",
    "name" => "Panzerotti Maxi",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/0f/f5/bc/b2/un-panzerotto-esagerato.jpg",
    "visible" => true,
  ],
  // 18
  [ "user_id" => "18",
    "name" => "Crocchette Di Pollo",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://i0.wp.com/www.pizzeriagirasole.net/wp-content/uploads/2020/07/FT_107324053.jpg?fit=640%2C400&ssl=1",
    "visible" => true,
  ],
  [
    "user_id" => "18",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://d2sj0xby2hzqoy.cloudfront.net/kenwood_italy/attachments/data/000/007/417/medium/panzerotti.jpg",
    "visible" => true,
  ],
  [ "user_id" => "18",
    "name" => "Crocchette Di Pollo Maxi",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://blog.giallozafferano.it/loti64/wp-content/uploads/2013/03/IMG_6120.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "18",
    "name" => "Panzerotti Dolci",
    "ingredients" => "Nutella, panna",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://cottoecrudo.it/wp-content/uploads/2020/01/Panzerotti-dolci-alla-Nutella.jpg",
    "visible" => true,
  ],
  [ "user_id" => "18",
    "name" => "Chicken Wings",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/classic-buffalo-wings-horizontal-279-1547506155.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "18",
    "name" => "Panzerotti Al Pomodoro",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://blog.giallozafferano.it/rossellainpadella/wp-content/uploads/2020/03/PANZEROTTI-LAMPO-SENZA-LIEVITAZIONE.jpg",
    "visible" => true,
  ],
  // 19
  [
    "user_id" => "19",
    "name" => "Crocchette Di Pollo",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://www.tuorlorosso.it/wp-content/uploads/2021/06/Nugget-di-pollo-1.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "19",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/vimdb/80350_223-97-3982-3982.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "19",
    "name" => "Crocchette Di Pollo Doppie",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://blog.cookaround.com/ledeliziedipepi/wp-content/uploads/2018/10/Crocchette-di-pollo-dal-cuore-filante-1.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "19",
    "name" => "Panzerotti Fritti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://primochef.it/wp-content/uploads/2017/06/SH_panzerotto-1200x800.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "19",
    "name" => "nuggets Americani",
    "ingredients" => "panino, petto di pollo, inslata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://www.foodblog.it/wp-content/uploads/2020/08/nuggets-di-pollo-ricetta-americana-1-1280x720.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "19",
    "name" => "Panzerotti Fritti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.ilboccatv.com/wp-content/uploads/Panzerotti-fritti-ilboccatv.jpg",
    "visible" => true,
  ],
  // 20
  [
    "user_id" => "20",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://blog.giallozafferano.it/francinut87/wp-content/uploads/2021/04/Pizza-margherita-fatta-in-casa-orizzontale.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "20",
    "name" => "Quattro Stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://www.ricettedalmondo.it/images/foto-ricette/p/29526-pizza-quattro-stagioni.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "20",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://www.agrodolce.it/app/uploads/2019/03/margherita-con-bufala-finale.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "20",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/97C2C718-5015-437F-8355-316EE000F57C/Derivates/556409BB-02E0-4BA3-BC16-F409F609FCED.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "20",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://i0.wp.com/www.ibocconighiottidilolly.it/wp-content/uploads/2021/04/IMG_6379-compressed-scaled.jpg?resize=750%2C500&ssl=1",
    "visible" => true,
  ],
  [
    "user_id" => "20",
    "name" => "Funghi e Cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://i1.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2019/10/4102_Pizza.jpg?resize=895%2C616&ssl=1",
    "visible" => true,
  ],
  // 21
  [
    "user_id" => "21",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://blog.giallozafferano.it/francinut87/wp-content/uploads/2021/04/Pizza-margherita-fatta-in-casa-orizzontale.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "21",
    "name" => "Quattro Stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://www.petitchef.it/imgupl/recipe/pizza-quattro-stagioni--327908p533338.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "21",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/0e/9c/ab/14/pizza-margherita-con.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "21",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://www.vesuviolive.it/wp-content/uploads/2021/03/pizza-marinara-600x337.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "21",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/07/8e/f2/d4/pizza-salsiccia-friarielli.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "21",
    "name" => "Funghi e Cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://locali.food-zone.it/images/alimenti/IMG-20180606-WA0003.jpg",
    "visible" => true,
  ],
  // 22
  [
    "user_id" => "22",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://static.cookist.it/wp-content/uploads/sites/21/2018/04/pizza-margherita-fatta-in-casa.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "22",
    "name" => "Quattro Stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2016/07/3017_Pizza.jpg?resize=895%2C616&ssl=1",
    "visible" => true,
  ],
  [
    "user_id" => "22",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/16/53/fa/83/pizza-con-mozzarella.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "22",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://cdn.tasteatlas.com//images/dishrestaurants/d437c913df5349a9adce597d1924f310.jpg?width=800&height=513",
    "visible" => true,
  ],
  [
    "user_id" => "22",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2016/12/1481015550_22f4b242807467cef0fc08da1ab06a94299f1123-1015500919.jpg?w=580",
    "visible" => true,
  ],
  [
    "user_id" => "22",
    "name" => "Funghi e Cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/2014_Pizza_con_funghi_e_prosciutto_cotto_e_mozzarella_di_bufala.jpg/1280px-2014_Pizza_con_funghi_e_prosciutto_cotto_e_mozzarella_di_bufala.jpg",
    "visible" => true,
  ],
  // 23
  [
    "user_id" => "23",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://www.scattidigusto.it/wp-content/uploads/2018/03/pizza-margherita-originale-Scatti-di-Gusto.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "23",
    "name" => "Quattro Stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/05/de/78/71/da-raffaele.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "23",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://i.pinimg.com/originals/04/f1/eb/04f1eb4d7402bf314e367592b0d1ba01.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "23",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://garage.pizza/wp-content/uploads/2020/01/0O1A6684-570x570.jpeg",
    "visible" => true,
  ],
  [
    "user_id" => "23",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://www.alice.tv/img/cache/610x380/media/ricette/9xv1jc1/pizza-provola-salsiccia.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "23",
    "name" => "Funghi e Cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/0c/aa/dd/b1/pizza-con-funghi-e-prosciutto.jpg",
    "visible" => true,
  ],
  // 24
  [
    "user_id" => "24",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://reportergourmet.com/files/2020/06/pizza-margherita.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "24",
    "name" => "Quattro Stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://img.myloview.it/quadri/pizza-italiana-fresca-quattro-stagioni-pizza-quattro-stagioni-sulla-tavola-di-legno-sul-tavolo-da-cucina-con-diversi-ingredienti-brillanti-messa-a-fuoco-selettiva-700-95490049.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "24",
    "name" => "Bufala",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://www.tacoloco.it/wp-content/uploads/2018/01/pizza-bufalina.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "24",
    "name" => "Marinara",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://www.dissapore.com/wp-content/uploads/2015/08/Pizza-marinara.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "24",
    "name" => "Patate e Salsiccia",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://images.squarespace-cdn.com/content/v1/5d7579baa3162a41342e3b89/1609519003712-79A6RA6SYIJ3GKV480JD/LF_tonda+%289+of+17%29.jpg?format=1000w",
    "visible" => true,
  ],
  [
    "user_id" => "24",
    "name" => "Funghi e Cotto",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://res.cloudinary.com/tf-lab/image/upload/w_600,h_337,c_fill,g_auto:subject,q_auto,f_auto/restaurant/00942682-b2f8-40b1-b355-84ee3786235f/271ab8ac-e5fe-4df5-9f12-ae954f4d4f20.jpg",
    "visible" => true,
  ],
  // 25
  [
    "user_id" => "25",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2011/09/ricetta-uramaki-gamberi-avocado/_jcr_content/header-par/image_single.img.jpg/1466425275386.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "25",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://matsu-sushi.it/wp-content/uploads/2020/05/nigiri-salmone-1.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "25",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "http://images.sweetauthoring.com/recipe/317662_779.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "25",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/0e/a4/f5/13/nigiri-scottato.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "25",
    "name" => "Uramaki Di Pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/fdl_content_import_it/uramaki-pollo-fritto.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "25",
    "name" => "Barca Di Sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "http://sea-breeze.it/wp-content/uploads/2019/10/barca-di-sushi.png",
    "visible" => true,
  ],
  // 26
  [
    "user_id" => "26",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "http://images.sweetauthoring.com/recipe/317656_779.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "26",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://primochef.it/wp-content/uploads/2021/10/SH_nigiri_salmone.jpg.webp",
    "visible" => true,
  ],
  [
    "user_id" => "26",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkIvBmdAuU8DX_7046qvmy86WijJl5Cr6R1g&usqp=CAU",
    "visible" => true,
  ],
  [
    "user_id" => "26",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://www.kanjimilano.com/ke/wp-content/uploads/2020/11/NIGIRI-SAKE-SCOTTATO.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "26",
    "name" => "Uramaki Di Pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "http://sushikayo.it/wp-content/uploads/2019/05/128-uramaki-chicken.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "26",
    "name" => "Barca Di Sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "https://www.lucianopignataro.it/wp-content/uploads/2017/02/FOTO-N-3-e1487055637636.jpg",
    "visible" => true,
  ],
  // 27
  [
    "user_id" => "27",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://static.cosaporto.it/media/2020/06/uramaki-spicy-salm-tart_Basara_cosaporto-768x768-1-600x600.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "27",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://izzycooking.com/wp-content/uploads/2021/03/Nigiri-thumbnail.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "27",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "http://images.sweetauthoring.com/recipe/317662_779.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "27",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://thumbs.dreamstime.com/b/decorazione-di-color-salmone-scottata-del-formaggio-e-della-maionese-dei-sushi-di-nigiri-cucina-giapponese-60062141.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "27",
    "name" => "Uramaki Di Pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.oyosushidalmine.it/wp-content/uploads/2020/05/75.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "27",
    "name" => "Barca Di Sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "https://img.grouponcdn.com/deal/v9wcKcdD1EDHBw6PgHX6/ef-700x420/v1/c870x524.jpg",
    "visible" => true,
  ],
  // 28
  [
    "user_id" => "28",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.deabyday.tv/.imaging/mte/deabyday/1600x1038/article/guides/cucina-e-ricette/primi/Uramaki-philadelphia-e-tonno--senza-pesce-crudo-/imageOriginal/Uramaki-senza-crudo.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "28",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://www.sushikingparma.it/sushi/wp-content/uploads/2018/01/sushuking-nighiri.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "28",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.irorisushiathome.it/wp-content/uploads/2020/08/uramaki_2_unagi_rainbow9.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "28",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://www.sakurarc.it/wp-content/uploads/2020/04/63.-nigiri-philadelphia.-scaled.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "28",
    "name" => "Uramaki Di Pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.fusionrestaurant.it/wp-content/uploads/2020/05/24-uramaki-chicken-roll.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "28",
    "name" => "Barca Di Sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "https://img.grouponcdn.com/deal/3gzJuM2qZCEnL5L6xYJehXrMJWvn/3g-960x576/v1/t600x362.jpg",
    "visible" => true,
  ],
  // 29
  [
    "user_id" => "29",
    "name" => "Uramaki",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.sushibo.it/wp-content/uploads/2021/05/sushibo_uramaki_sake_menu-e1628794029864.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "29",
    "name" => "Nigiri",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://www.jingdu.it/wp-content/uploads/2020/12/nigiri-salmone.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "29",
    "name" => "Uramaki Rainbow",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://img.freepik.com/free-photo/set-rainbow-uramaki-sushi-rolls-with-tuna-salmon-avocado-served-restaurant-bamboo-mat_126745-3019.jpg?w=2000",
    "visible" => true,
  ],
  [
    "user_id" => "29",
    "name" => "Nigiri Scottati",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.00",
    "cover" => "https://www.sushitecazen.it/wp-content/uploads/2019/09/Nigiri-salmone-alla-fiamma.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "29",
    "name" => "Uramaki Di Pollo",
    "ingredients" => "riso, alga, avocado, polpa di granchio",
    "description" => "Uramaki è un piatto tipico della cucina giapponese a base di riso",
    "price" => "8.50",
    "cover" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/ricetta-ebi-uramaki.jpg?itok=bwmLlxJR",
    "visible" => true,
  ],
  [
    "user_id" => "29",
    "name" => "Barca Di Sushi",
    "ingredients" => "riso, filetto di salmone, branzino, filetto di tonno",
    "description" => "Nigiri è un piatto tipico della cucina giapponese a base di riso",
    "price" => "13.00",
    "cover" => "https://img.freepik.com/premium-photo/set-maki-sushi-wooden-boat-tray_93675-102116.jpg?size=626&ext=jpg",
    "visible" => true,
  ],
  //30
  [
    "user_id" => "30",
    "name" => "Pizza Fritta Gourmet",
    "ingredients" => "pastella, olio, prosciutto crudo, pecorino",
    "description" => "Deliziose pizze fritte con selezione di salumi e formaggi",
    "price" => "9.80",
    "cover" => "https://corrieredelvino.it/wp-content/uploads/2022/03/APERT-Pizza-Fritta-1280x720.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "30",
    "name" => "Trippa Di Maiale",
    "ingredients" => "Budella di maiale, passata di pomodoro, pepe",
    "description" => "Trippa al sugo buonissima",
    "price" => "5.00",
    "cover" => "http://www.lacucinadibacco.it/wp-content/uploads/2018/01/Trippa-al-sugo-alla-calabrese.jpg",
    "visible" => true,
  ],
  [ "user_id" => "30",
    "name" => "Crocchette Di Pollo",
    "ingredients" => "panino, petto di pollo, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del petto di pollo avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://cdn.robadadonne.it/wp-content/uploads/sites/4/2017/07/12161045/0485e7d239cf336531fc4dc9ca59af7a-640x320.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "30",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXyBSpfE38Y0ietA5S-FI17sQ7ojmPExO6iQ&usqp=CAU",
    "visible" => true,
  ],
  [
    "user_id" => "30",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://www.bofrost.it/writable/products/images-v2/15317_r.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "30",
    "name" => "Quattro Stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://trentapizza.co.uk/wp-content/uploads/2016/07/pizza-quatro-stagioni.jpg",
    "visible" => true,
  ],
  // 31
  [
    "user_id" => "31",
    "name" => "Pizza Fritta Gourmet",
    "ingredients" => "pastella, olio, gambero, pecorino",
    "description" => "Deliziose pizze fritte con selezione di pesce e formaggi",
    "price" => "9.80",
    "cover" => "https://www.ilgiornaledelcibo.it/wp-content/uploads/2017/04/fucina.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "31",
    "name" => "Trippa Di Branzino",
    "ingredients" => "Budella di branzino, passata di pomodoro, pepe",
    "description" => "Trippa al sugo buonissima",
    "price" => "5.00",
    "cover" => "https://www.marblu.it/wp-content/uploads/2018/08/Cesare-1-876x500.jpg",
    "visible" => true,
  ],
  [ "user_id" => "31",
    "name" => "Crocchette Di Pesce",
    "ingredients" => "panino, pesce, insalata, salsa mcChicken",
    "description" => "Tutta la semplicità del pesce avvolto in una panatura croccante, insieme all’insalata iceberg e all’inconfondibile salsa McChicken.",
    "price" => "3.90",
    "cover" => "https://blog.giallozafferano.it/lacucinadiloredana/wp-content/uploads/2017/09/polpette-di-pesce-e-patate.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "31",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2019/01/panzerotti-al-forno/jcr:content/header-par/image-single.img10.jpg/1548337377491.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "31",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://wips.plug.it/cips/buonissimo.org/cms/2012/05/pizza.jpg?w=713&a=c&h=407",
    "visible" => true,
  ],
  [
    "user_id" => "31",
    "name" => "Quattro Stagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://media-cdn.tripadvisor.com/media/photo-s/05/de/78/71/da-raffaele.jpg",
    "visible" => true,
  ],
  // 32
  [
    "user_id" => "32",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://blog.giallozafferano.it/toniaincucina/wp-content/uploads/2020/03/panzerotti-pugliesi-1-3.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "32",
    "name" => "Margherita",
    "ingredients" => "pomodoro, mozzarella, olio",
    "description" => "La pizza Margherita è la tipica pizza napoletana, condita con pomodoro, mozzarella.",
    "price" => "5.40",
    "cover" => "https://citynews-napolitoday.stgy.ovh/~media/original-hi/52532125295087/pizza-margherita-2-3.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "32",
    "name" => "QuattroStagioni",
    "ingredients" => "carciofi, mozzarella, olio, funghi, Prosciutto cotto, olive nere",
    "description" => "La quattro stagioni viene disposta in quattro angoli dell’impasto a simulare appunto le 4 stagioni che si susseguono nell’anno e portarla in tavola quando non avete idee per pranzo e cena",
    "price" => "5.70",
    "cover" => "https://www.ricettadicucina.com/upload/recipe/0/9/c/df9664b1c90e1815a31388fe741b6168eb0a908e.jpg?1574416949",
    "visible" => true,
  ],
  [
    "user_id" => "32",
    "name" => "Panzerotti",
    "ingredients" => "pomodoro, mozzarella, pepe, olio",
    "description" => "Sfiziose mezzelune dorate, ripiene di pomodoro e Mozzarella.",
    "price" => "3.40",
    "cover" => "https://www.ricettedellanonna.net/wp-content/uploads/2011/03/panzerotti-ripieni.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "32",
    "name" => "Marinara",
    "ingredients" => "pomodoro, olio, aglio",
    "description" => "La pizza Marinara è la tipica pizza napoletana, condita con pomodoro e aglio",
    "price" => "5.80",
    "cover" => "https://d2j6dbq0eux0bg.cloudfront.net/images/39797794/2468346486.jpg",
    "visible" => true,
  ],
  [
    "user_id" => "32",
    "name" => "Pizza Patatine e Wurstel",
    "ingredients" => "patatine fritte, wurstel, pomodoro e mozzarella",
    "description" => "Classica pizza con base rossa e mozzarella, condita con patatine e wurstel",
    "price" => "5.70",
    "cover" => "https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/11/3244_Pizza.jpg?resize=895%2C616&ssl=1",
    "visible" => true,
  ],
  // 33
  [ "user_id" => "33",
    "name" => "cotoletta Alla Milanese",
    "ingredients" => "costoletta di vitello, uova, pepe farina",
    "description" => "La cotoletta alla milanese è uni dei piatti più tipici e conosciuti di Milano.",
    "price" => "10.00",
    "cover" => "https://www.deabyday.tv/dam/jcr:fde2bb00-bff0-4c30-ad65-91f6d7d0a828/cottura-cotoletta-alla-milanese.2020-12-01-17-36-27",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Tortellini In Brodo",
    "ingredients" => "tortellini, brodo di manzo",
    "description" => "I tortellini sono una pasta all'uovo ripiena, tipica di Bologna.",
    "price" => "7.50",
    "cover" => "https://www.oggi.it/cucina/wp-content/uploads/sites/19/2014/07/TORTELLINI-IN-BRODO-DELLA-VIGILIA-g-470x377.jpg",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Lasagna",
    "ingredients" => "sfoglia, besciamella, ragù",
    "description" => "Le lasagne al forno sono costituite da una sfoglia di pasta all'uovo tagliata in fogli grossolanamente rettangolari detti lasagne",
    "price" => "9.00",
    "cover" => "https://www.scattidigusto.it/wp-content/uploads/2016/02/lasagna-ricetta-perfetta-480x270.jpg",
    "visible" => true,
  ],

  [ "user_id" => "33",
    "name" => "Pastae Patate",
    "ingredients" => "patate, carote, pepe, olio",
    "description" => "La Pasta e patate è un primo piatto tipico della cucina napoletana",
    "price" => "6.40",
    "cover" => "https://www.cucinasud.it/images/2020/05/02/pastastorica_large.jpg",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Cuoppo Di Mare",
    "ingredients" => "calamari, gamberi, triglia, semola, olio",
    "description" => "Il Cuoppo di Pesce è un piatto tipico della cucina campana",
    "price" => "5.30",
    "cover" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShCEzEdU5-7xpbWy0xHxM2ffsDXk24jvx2GA&usqp=CAU",
    "visible" => true,
  ],
  [ "user_id" => "33",
    "name" => "Orecchiette Con Le Cime Rape",
    "ingredients" => "cime di rapa, aglio, acciughe, olio",
    "description" => "Le orecchiette con cime di rapa è uno dei primi piatti più conosciuti dalla tradizione della cucina pugliese",
    "price" => "6.30",
    "cover" => "https://www.carapelli.it/wp-content/uploads/2019/01/orecchiette-cime-di-rapa-600x390.jpg",
    "visible" => true,
  ],
];
