<?php

use Illuminate\Support\Facades\Config;

return [
  // osteria
  // romana
  [
    "email" => "paxine5145@doerma.com",
    "password" => "1234",
    "business_name" => "l'osteria di monteverde roma",
    "street_address" => "Via Pietro Cartoni, 163/165",
    "phone_number" => "0653273887",
    "cover" => "",
  ],
  // milanese
  [
    "email" => "paxexo1018@duetube.com",
    "password" => "1234",
    "business_name" => "osteria dell'oca giuliva",
    "street_address" => "Viale Bligny, 29",
    "phone_number" => "0258312871",
    "cover" => "",
  ],
  // bolognese
  [
    "email" => "wanon70822@cupbest.com",
    "password" => "1234",
    "business_name" => "Antica Osteria Le Mura",
    "street_address" => "Vicolo del Falcone, 13/a",
    "phone_number" => "0510015254",
    "cover" => "",
  ],
  //napoletana
  [
    "email" => "wigel64467@doerma.com",
    "password" => "1234",
    "business_name" => "osteria il gobbetto",
    "vat_number" => "",
    "street_address" => "Via Sergente Maggiore, 8",
    "phone_number" => "0812512435",
    "cover" => "",
  ],
  // barese
  [
    "email" => "wigel64467@doerma.com",
    "password" => "1234",
    "business_name" => "osteria le arpie",
    "street_address" => "Arco del Carmine, 2",
    "phone_number" => "0805217988",
    "cover" => "",
  ],
  //bar
  [
    "email" => "dobeg66940@cupbest.com",
    "password" => "1234",
    "business_name" => "caffè del kassaro",
    "street_address" => "Via Vittorio Emanuele, 390",
    "phone_number" => "0915070023",
    "cover" => "",
  ],
  [
    "email" => "jofahem925@dakcans.com",
    "password" => "1234",
    "business_name" => "caffè capranica",
    "street_address" => "Piazza Capranica, 75/77",
    "phone_number" => "0669921720",
    "cover" => "",
  ],
  [
    "email" => "kafova8498@duetube.com",
    "password" => "1234",
    "business_name" => "caffè capranica",
    "street_address" => "Piazza Capranica, 75/77",
    "phone_number" => "064885617",
    "cover" => "",
  ],
  [
    "email" => "mojeno2228@doerma.com",
    "password" => "1234",
    "business_name" => "caffetteria massimo",
    "street_address" => "Via Giovanni Amendola, 6",
    "phone_number" => "064870860",
    "cover" => "",
  ],
  [
    "email" => "paxine5145@doerma.com",
    "password" => "1234",
    "business_name" => "Cuccuma Caffè",
    "street_address" => "Via San Giovanni Maggiore Pignatelli, 1a",
    "phone_number" => "08119708587",
    "cover" => "",
  ],
  // Burger King
  [
    "email" => "BurgerKing@cupbest.com",
    "password" => "1234",
    "business_name" => "Burger King",
    "street_address" => "Piazzale Luigi Cadorna, 16",
    "phone_number" => "028053860",
    "cover" => "",
  ],
  [
    "email" => "BurgerKingEdoardoJenner@cupbest.com",
    "password" => "1234",
    "business_name" => "Burger King",
    "street_address" => "Viale Edoardo Jenner, 51",
    "phone_number" => "0280011050",
    "cover" => "",
  ],
  // McDonald
  [
    "email" => "McDonaldMilanoDuomo@cupbest.com",
    "password" => "1234",
    "business_name" => "McDonald's Milano Duomo",
    "street_address" => "Passaggio Duomo, 2",
    "phone_number" => "0286997265",
    "cover" => "",
  ],
  [
    "email" => "McDonaldMilanoViaTorino@cupbest.com",
    "password" => "1234",
    "business_name" => "McDonald's Milano Via Torino",
    "street_address" => "Via Torino, 68",
    "phone_number" => "3408484034",
    "cover" => "",
  ],
  //fast food
  [
    "email" => "nameyeh418@doerma.com",
    "password" => "1234",
    "business_name" => "fast24",
    "street_address" => "Via Sorio, 64/A",
    "phone_number" => "3451737833",
    "cover" => "",
  ],
  [
    "email" => "reviloc149@dakcans.com",
    "password" => "1234",
    "business_name" => "polletti san bartolomeo",
    "street_address" => "Viale della Moschea, 206",
    "phone_number" => "068075659",
    "cover" => "",
  ],
  [
    "email" => "yipabaf690@doerma.com",
    "password" => "1234",
    "business_name" => "SPECIAL hamburger & italian Fast Food",
    "street_address" => "Via Lecco, 4",
    "phone_number" => "0229537233",
    "cover" => "",
  ],
  [
    "email" => "demew11458@doerma.com",
    "password" => "1234",
    "business_name" => "speedy grill",
    "street_address" => "Via Principe di Piemonte, 57/C",
    "phone_number" => "3349408764",
    "cover" => "",
  ],
  [
    "email" => "nerod25859@doerma.com",
    "password" => "1234",
    "business_name" => "Elen Fast Food",
    "street_address" => "corso dei mille, 94/96",
    "phone_number" => "3892467205",
    "cover" => "",
  ],
  //pizza
  [
    "email" => "xijajex434@cupbest.com",
    "password" => "1234",
    "business_name" => "il veliero pizzeria",
    "slug" => "",
    "vat_number" => "",
    "street_address" => "Via delle Belle Arti, 14",
    "phone_number" => "051225581",
    "cover" => "",
  ],
  [
    "email" => "jifid10528@cupbest.com",
    "password" => "1234",
    "business_name" => "pizza della madonna dei monti",
    "slug" => "",
    "vat_number" => "",
    "street_address" => "Via della Madonna dei Monti, 110",
    "phone_number" => "0669413112",
    "cover" => "",
  ],
  [
    "email" => "venas77655@doerma.com",
    "password" => "1234",
    "business_name" => "pizzeria speranzella",
    "street_address" => "Via Speranzella, 84",
    "phone_number" => "08118196384",
    "cover" => "",
  ],
  [
    "email" => "honey38413@dakcans.com",
    "password" => "1234",
    "business_name" => "pizzeria dei pirati",
    "street_address" => "Via Rionero, 38",
    "phone_number" => "0883522901",
    "cover" => "",
  ],
  [
    "email" => "giheb25464@doerma.com",
    "password" => "1234",
    "business_name" => "pizzeria sansovino",
    "street_address" => "Calle Zaguri, 2628",
    "phone_number" => "0415286141",
    "cover" => "",
  ],
  // cinese
  [
    "email" => "lohabim316@cupbest.com",
    "password" => "1234",
    "business_name" => "koi sushi",
    "street_address" => "Via Regina Margherita, 310",
    "phone_number" => "3496291775",
    "cover" => "",
  ],
  [
    "email" => "sotif39863@duetube.com",
    "password" => "1234",
    "business_name" => "jubin due",
    "street_address" => "Via Padova, 7",
    "phone_number" => "0226141020",
    "cover" => "",
  ],
  [
    "email" => "wasawet730@dakcans.com",
    "password" => "1234",
    "business_name" => "bin hai",
    "street_address" => "Via la Spezia, 86",
    "phone_number" => "067012519",
    "cover" => "",
  ],
  [
    "email" => "tebox94225@doerma.com",
    "password" => "1234",
    "business_name" => "hana",
    "street_address" => "Viale della Croce Rossa, 27",
    "phone_number" => "0916788305",
    "cover" => "",
  ],
  [
    "email" => "kenixa8009@dakcans.com",
    "password" => "1234",
    "business_name" => "yoma",
    "street_address" => "Via Fossalta, 3",
    "phone_number" => "051226592",
    "cover" => "",
  ],
];
